name: 🐛 Bug Report
description: "File a bug report for the project"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**
  - type: input
    id: version
    attributes:
      label: 🔢 Version
      description: What version of the software are you running?
      placeholder: e.g. 1.0.2, commit hash, or 'latest'
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Where is this bug occurring?
      options:
        - Production
        - Staging
        - Development
        - Testing
        - Local Setup
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 🤔 What happened?
      description: Describe the bug and what you expected to happen instead.
      placeholder: A clear and concise description of the bug...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 👣 Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Perform '....'
        3. Observe '....'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 📓 Relevant log output or error messages
      description: Please copy and paste any relevant logs or error messages. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: 🖥️ System Information
      description: Please provide relevant system information (OS, hardware, cloud provider, etc.)
      placeholder: |
        - OS: [e.g. iOS, Windows, Linux]
        - Hardware/Device: [e.g. iPhone6, Raspberry Pi 4]
        - Cloud Provider (if applicable): [e.g. AWS, Azure, GCP]
        - Any other relevant system details...
  - type: checkboxes
    id: terms
    attributes:
      label: 🔍 Preflight Checklist
      description: "By submitting this issue, you agree to the following:"
      options:
        - label: I have searched the existing issues and this is a new, non-duplicate bug
          required: true
        - label: I have provided all the necessary information to understand and reproduce this bug
          required: true
  - type: textarea
    id: additional
    attributes:
      label: ➕ Additional context
      description: Add any other context about the problem here (screenshots, related issues, suggestions on how to fix, etc.)